@echo off 
start www.xhamster.com 
start www.xvideos.com
start www.pornotube.com
start www.videosrobados.com
start www.beeg.com 
start www.leche69.com
start www.rubias19.com
start www.cerdas.com
start www.redtube.com
start www.muyzorras.com
start www.videooporno.com
start www.puritanas.com/
start www.tuporno.tv
start www.pornotuyo.es
start www.babosas.com
start www.video.xnxx.com
start www.culioneros.com
start www.cumlouder.com 
start www.poringa.net 
start www.puritanas.com 
start www.xnxx.com 
start www.reyalmeja.com 
start www.petardas.com 
start www.muyzorras.com 
start www.planetazorras.com 
start www.peterpaulxxx.com 
start www.videospornodetv.com 
start www.putogle.com 
start www.castigados.com 
start www.iberporno.com 
start www.laxtana.com
msg * Upaa!!! que haces viendo esto! 
exit